# CareRoute AI - Multilingual Symptoms

SYMPTOMS = [
    "Headache",
    "Fever",
    "Cough",
    "Shortness of breath",
    "Chest discomfort",
    "Palpitations",
    "Abdominal pain",
    "Nausea",
    "Vomiting",
    "Diarrhea",
    "Joint pain",
    "Back pain",
    "Skin rash",
    "Itching",
    "Ear pain",
    "Hearing difficulty",
    "Sore throat",
    "Nasal congestion",
    "Eye pain",
    "Blurred vision",
    "Dizziness",
    "Numbness",
    "Fatigue"
]


TRANSLATIONS = {

    "English": {
        "Headache": "Headache",
        "Fever": "Fever",
        "Cough": "Cough",
        "Shortness of breath": "Shortness of breath",
        "Chest discomfort": "Chest discomfort",
        "Palpitations": "Palpitations",
        "Abdominal pain": "Abdominal pain",
        "Nausea": "Nausea",
        "Vomiting": "Vomiting",
        "Diarrhea": "Diarrhea",
        "Joint pain": "Joint pain",
        "Back pain": "Back pain",
        "Skin rash": "Skin rash",
        "Itching": "Itching",
        "Ear pain": "Ear pain",
        "Hearing difficulty": "Hearing difficulty",
        "Sore throat": "Sore throat",
        "Nasal congestion": "Nasal congestion",
        "Eye pain": "Eye pain",
        "Blurred vision": "Blurred vision",
        "Dizziness": "Dizziness",
        "Numbness": "Numbness",
        "Fatigue": "Fatigue"
    },

    "Telugu": {
        "Headache": "తలనొప్పి",
        "Fever": "జ్వరం",
        "Cough": "దగ్గు",
        "Shortness of breath": "శ్వాస తీసుకోవడంలో ఇబ్బంది",
        "Chest discomfort": "ఛాతీలో అసౌకర్యం",
        "Palpitations": "గుండె దడ",
        "Abdominal pain": "కడుపు నొప్పి",
        "Nausea": "వికారం",
        "Vomiting": "వాంతులు",
        "Diarrhea": "విరేచనాలు",
        "Joint pain": "కీళ్ల నొప్పి",
        "Back pain": "వెన్నునొప్పి",
        "Skin rash": "చర్మంపై దద్దుర్లు",
        "Itching": "దురద",
        "Ear pain": "చెవి నొప్పి",
        "Hearing difficulty": "వినికిడి సమస్య",
        "Sore throat": "గొంతు నొప్పి",
        "Nasal congestion": "ముక్కు దిబ్బడ",
        "Eye pain": "కంటి నొప్పి",
        "Blurred vision": "చూపు మసకబారడం",
        "Dizziness": "తల తిరగడం",
        "Numbness": "తిమ్మిరి",
        "Fatigue": "అలసట"
    },

    "Hindi": {
        "Headache": "सिरदर्द",
        "Fever": "बुखार",
        "Cough": "खांसी",
        "Shortness of breath": "सांस लेने में कठिनाई",
        "Chest discomfort": "सीने में असहजता",
        "Palpitations": "दिल की धड़कन तेज होना",
        "Abdominal pain": "पेट दर्द",
        "Nausea": "मतली",
        "Vomiting": "उल्टी",
        "Diarrhea": "दस्त",
        "Joint pain": "जोड़ों का दर्द",
        "Back pain": "कमर दर्द",
        "Skin rash": "त्वचा पर चकत्ते",
        "Itching": "खुजली",
        "Ear pain": "कान में दर्द",
        "Hearing difficulty": "सुनने में कठिनाई",
        "Sore throat": "गले में खराश",
        "Nasal congestion": "नाक बंद होना",
        "Eye pain": "आंखों में दर्द",
        "Blurred vision": "धुंधला दिखाई देना",
        "Dizziness": "चक्कर आना",
        "Numbness": "सुन्नपन",
        "Fatigue": "थकान"
    }
}